# Site Settings
title: indscience.org
email: contact@indscience.org
description: >
   indscience.org publish articles or graphics related to 
   physics, earth science, medicine, nanotechnology, electronics, space, biology, chemistry, computer sciences, engineering, mathematics and other sciences and technologies.
baseurl: ""
url: "https://indscience.org"
twitter_username: indscience
github_username:  indscience
instagram_username: indscience
facebook_username: indscience
# Build Settings
sass:
  sass_dir: _sass
      
kramdown:
  input: GFM


# SEO stuff
google_site_verification: "n4cO5YKmFSGx9GcwtzNuw3RSm3yMbS30isHdyOK2sPg"
bing_webmastertools_id: ""
yandex_site_verification :
naver_site_verification  :

